apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  namespace: default
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: model
  endpoints:
  - port: http-metrics  # Reference by name
    interval: 30s
    path: /metrics
