apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"streamlit"},"name":"streamlit","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"streamlit"}},"strategy":{},"template":{"metadata":{"labels":{"app":"streamlit"}},"spec":{"containers":[{"image":"containerssimplified/streamlit:v1","name":"streamlit","ports":[{"containerPort":8501}],"resources":{}}]}}},"status":{}}
  creationTimestamp: "2026-01-23T05:40:35Z"
  generation: 1
  labels:
    app: streamlit
  name: streamlit
  namespace: default
  resourceVersion: "2177"
  uid: 7345b709-f726-41ff-9a85-d38f5eae5088
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: streamlit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - image: containerssimplified/streamlit:v1
        imagePullPolicy: IfNotPresent
        name: streamlit
        ports:
        - containerPort: 8501
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-23T05:41:11Z"
    lastUpdateTime: "2026-01-23T05:41:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-23T05:40:35Z"
    lastUpdateTime: "2026-01-23T05:41:11Z"
    message: ReplicaSet "streamlit-7cf58954dc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  terminatingReplicas: 0
  updatedReplicas: 1
